### PR TITLE
[BACKLOG-35298] Upgrade security-web dependency

### PR DESCRIPTION
**Pull request by dcleao**
@bennychow, @ddiroma please review.

Depends on: https://github.com/pentaho/security-web/pull/11

### CODE REVIEW

**Comment by dcleao** [comment]
@jmcrfp please review.

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 43s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Review by bennychow — APPROVED** [review]

**Comment by ddiroma** [comment]
@dcleao Approved

**Comment by dcleao** [comment]
@cardosov, @graimundo, @hbfernandes, @jmcrfp, @lgrill-pentaho, @smaring, @tmcsantos please review and merge.
Thanks

**Review by smaring — APPROVED** [review]

**Pull request merged**
