### PR TITLE
[ONE-95] add serverId to frontend plugin

### PR DESCRIPTION
**Pull request by smaring**

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 1m 56s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by smaring** [comment]
Doing some tests on this before merge.  We don't want an auth fail against the on-prem prior to the cutover.  Hopefully, the on-prem will just ignore the auth data.

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 1m 53s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 1m 27s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Pull request merged**
