### PR TITLE
[BACKLOG-35251] Java 11 compatibility

### PR DESCRIPTION
**Pull request by ricksjames**
Adding endorsed standards excluded from java 11 in preparation for java 11 changes to other repos.

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 55s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by emartin-hv** [comment]
@ricksjames Is there a test stack that has confirmed these parent poms don't break an entire end-to-end 9.3 QAT?

**Comment by ricksjames** [comment]
@emartin-hv no there is not, is that something you (engops) can setup easily? If not I can build one up locally.

**Comment by emartin-hv** [comment]
If you log a DEVO jira ticket for a test stack, we can test your change. For things like parent poms where a dependency can break the entire build, we like to be safe here.

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 46m 11s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 47s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Review by smaring — APPROVED** [review]

**Pull request merged**
